### ISSUE TITLE
關於日本豎排「！」「？」

### ISSUE THREAD

**Issue by yuanhao-chen-nyoeghau** [tanukihee/ChineseJFM#1]
在我讀過的豎排日文出版物中，「！」「？」若緊接文字，應空一格；若接標點符號，佔一格不空格。如

彼
だ
！

と
。
次
の
文
章
。
﹁
彼
だ
！
﹂
と
。

**Comment by tanukihee** [comment]
不只是竖排，横排也如此。或者说，当问号、感叹号作为「标号」或位于段末／其他符号前时，后不空一格，当作为「点号」且后方有其他文字时，后需空一格。

ujis 会自己空一格，但我觉得这一格需要手动加空。因为排版引擎并不会知到你用问号叹号时是作为标号还是点号用的，因此没有在后面加 glue。

中文中其实也有这样的用法。《标点符号用法》GB/T 15834-2011 中有如下规定：

![image](https://user-images.githubusercontent.com/34062491/93764119-29a76280-fc45-11ea-9118-c2e7841747f4.png)

这里的「编者？校者？」中的问号即是标号，若是在日文语境中，这里的问号后面亦不需要加空格。
