### ISSUE TITLE
能否做到比例假名和开明同时开启呢？

### ISSUE THREAD

**Issue by yuanhao-chen-nyoeghau** [tanukihee/ChineseJFM#2]
希望在开启`RawFeature={+palt,+kern}`时也能实现开明效果。
开启`RawFeature={+palt,+kern}`时，`prop` 这个jfm会使得句号也变为半宽的。`kmjh`的效果：
<img width="140" alt="スクリーンショット 2020-10-28 10 29 49" src="https://user-images.githubusercontent.com/42882301/97383416-88c55a80-1908-11eb-91ec-75bc2872e783.png">

**Comment by tanukihee** [comment]
把 jfm-kmjh.lua 中的 `[0] = {width = 1}` 改成 `[0] = {width = 'prop'}` 即可
![image](https://user-images.githubusercontent.com/34062491/97441952-43367b00-1964-11eb-982c-40d81bd1eba6.png)

**Comment by yuanhao-chen-nyoeghau** [comment]
能否新增文件呢？比如proportional kaiming `jfm-pk*.lua`

**Comment by tanukihee** [comment]
先这么用着吧…每种风格提供一个 JFM 文件太麻烦了，我决定用 JFM Feature 特性，把各种风格封装在一起，就像北川先生的那个版本一样。

**Comment by yuanhao-chen-nyoeghau** [comment]
好，期待 feature 也封裝這個功能

**Comment by tanukihee** [comment]
@edward-martyr 更新了，可以试用了

**Comment by yuanhao-chen-nyoeghau** [comment]
这个feature不会用……
```
\usepackage{luatexja-fontspec}
\setmainjfont[TateFeatures={JFM=ja_JP/{vert,kaiming}}]{I.Ming}
```
```
LuaTeX-ja error: File `jfm-ja_JP/{vert,kaiming}.lua' not found.
```

**Comment by tanukihee** [comment]
JFM features 特性要在 20200919 版本之后的 luatexja 才能用。你的版本是最新的吗？

更新宏包命令：
```bash
tlmgr update --self --all
```

**Comment by yuanhao-chen-nyoeghau** [comment]
運行成功，不過発覚読号還是有問題：

```
\usepackage{luatexja-fontspec}
\setmainjfont[YokoFeatures={JFM=ja_JP/{kaiming,prop}},RawFeature={+palt,+kern}]{GenRyuMin JP}
```
```
ねこみたいに，「にゃあ」にゃあと，鳴いている彼女？ねこみたいに。「にゃあ？」にゃあと、鳴いている，「彼女」。
```

<img width="627" alt="スクリーンショット 2020-11-01 18 07 16" src="https://user-images.githubusercontent.com/42882301/97800073-15577c00-1c6d-11eb-8126-d17b91ef0fdf.png">

**Comment by tanukihee** [comment]
其实我不太懂 opentype 特性……palt 特性对标点也有用吧，只要比例假名的话不开 palt，开 pkna 就没问题了。
```LaTeX
\setmainjfont{FOT-TsukuAOldMin Pr6N}
[
    YokoFeatures={JFM=ja_JP/{kaiming,prop}},
    RawFeature={+pkna,+kern}
]
```

![image](https://user-images.githubusercontent.com/34062491/97800746-b98ff180-1c72-11eb-84b7-d8564d8b6870.png)
