### ISSUE TITLE
使用 ltjtarticle 等文档类直排时无法指定 vert 特性

### ISSUE THREAD

**Issue by lhy7889678** [tanukihee/ChineseJFM#3]
Minimal (Not) Working Example:
```latex
\documentclass{ltjtarticle}
\usepackage{luatexja-fontspec}
\setmainjfont{Noto Serif CJK SC}[TateFeatures = {JFM = {zh_CN/{quanjiao , vert}}}]% 亦可改成其他字体

\begin{document}
你好，“世界”！
\end{document}
```

按照文档的说明，直排时应同时使用 `quanjiao/banjiao/kaiming` 和 `vert`。但上述 M(N)WE 编译后出现错误：
```
You must specify ONLY ONE feature among "quanjiao", "banjiao" and "kaiming".
```

我还尝试了
```latex
TateFeatures = {JFM = {zh_CN/quanjiao , vert}}% 去掉大括号
TateFeatures = {JFM = {zh_CN/vert}}
```
同样报错；
如果使用
```latex
TateFeatures = {JFM = {zh_CN/quanjiao}}
```
则报错 ``Package luatexja Error: bad JFM `zh_CN'.``；
如果使用
```latex
YokoFeatures = {JFM = {zh_CN/quanjiao}}
```
配合 `ltjarticle` 等文档类，则可以正常编译。

以上测试使用 MiKTeX 21.3 NEXT for Windows，LuaHBTeX 1.14.0，ltjtarticle 2020-09-30 v1.8f-ltj-20。

**Comment by tanukihee** [comment]
问题竟然在于 `JFM = {zh_CN/quanjiao , vert}` 逗号前后的空格 ` `……

改成 `JFM = {zh_CN/quanjiao,vert}` 就好了

我待会在文档中删掉空格

**Comment by tanukihee** [comment]
我向 luatexja 反映了这个问题，见 https://osdn.net/projects/luatex-ja/ticket/42500

看他们意见吧，我这边暂时先把空格去掉
