### ISSUE TITLE
quotation 环境下引号开头的首段缩进出现问题

### ISSUE THREAD

**Issue by glatavento** [tanukihee/ChineseJFM#4]
quote 环境也有相同的问题。

MWE
```
\documentclass[punct=zh_CN/quanjiao]{ctexart}
\begin{document}

\begin{quotation}
  测试测试测试

  测试测试测试

  测试测试测试

  测试测试测试
\end{quotation}

\begin{quotation}
  “测试测试测试”

  “测试测试测试”

  “测试测试测试”

  “测试测试测试”
\end{quotation}

\begin{quotation}
  （测试测试测试）

  （测试测试测试）

  （测试测试测试）

  （测试测试测试）
\end{quotation}

\end{document}

```

![image](https://user-images.githubusercontent.com/76601050/138588694-c6686643-bc4f-45e9-bf1a-84814a3b8b06.png)

**Comment by tanukihee** [comment]
已复现并修改，将在下个版本中的更新中修复。目前可以使用 `\inhibitglue` 暂时绕开。

事实上目前版本的 luatexja 自带的 JFM 也存在这个问题，此问题是由  `\item` 引起的（`quotation` 环境也基于 `list` 环境，用到了 `\item`）。

尝试以下代码：
```LaTeX
\documentclass{ltjarticle}
\usepackage{lua-visual-debug}

\begin{document}
\begin{enumerate}
    \item 「テスト」
    \item \mbox{}【テスト】
    \item \mbox{（}テスト）
    \item \<《テスト》
\end{enumerate}
\end{document}

```

得到效果：
![image](https://user-images.githubusercontent.com/34062491/156004140-eef83a2a-70e3-4feb-8593-601c1551a940.png)

可以看到，`\item` 后并没有视作是盒子的开头，而是被视作了 `'jcharbdd'`。因此在 JFM 中加入相关设置即可解决。
![image](https://user-images.githubusercontent.com/34062491/156007294-5132b932-0548-4b60-a7fa-f01aeba527a2.png)

修改后效果（字体变化请忽略）：
![image](https://user-images.githubusercontent.com/34062491/156007738-d5a301e6-ecbd-4b64-8fe3-d426f1f8d6b2.png)
